"Filed out from Dolphin Smalltalk"!

PackageManifest subclass: #ManifestBootstrap5Examples
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

ManifestBootstrap5Examples guid: (GUID fromString: '{d5774ca8-bad4-446f-8a9e-d8045fe67ae4}')!

ManifestBootstrap5Examples comment: 'I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser'!

!ManifestBootstrap5Examples categoriesForClass!Manifest! !

!ManifestBootstrap5Examples class methodsFor!

ruleLiteralArrayContainsSuspiciousTrueFalseOrNilRuleV1FalsePositive	##(Pragma ignoreForCoverage).	^ #(#(#(#RGMetaclassDefinition #(#'ManifestBootstrap5Examples class' #ManifestBootstrap5Examples)) #'2023-03-22T07:21:51.155877+01:00') )!

ruleLongMethodsRuleV1FalsePositive	##(Pragma ignoreForCoverage).	^ #(#(#(#RGMethodDefinition #(#SBSBadgeExample #renderExampleOn: #false)) #'2023-03-22T07:21:22.941608+01:00') )!

ruleRBStringConcatenationRuleV1FalsePositive	^ #(#(#(#RGMethodDefinition #(#SBSTypographieExample #renderExampleOn: #false)) #'2019-04-30T20:55:07.149209+02:00') )! !

!ManifestBootstrap5Examples class categoriesForMethods!
ruleLiteralArrayContainsSuspiciousTrueFalseOrNilRuleV1FalsePositive!code/critics!public! !
ruleLongMethodsRuleV1FalsePositive!code/critics!public! !
ruleRBStringConcatenationRuleV1FalsePositive!code/critics!public! !
!

