"Filed out from Dolphin Smalltalk"!

SBSGenericTag subclass: #SBSAccordionBodyTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSAccordionBodyTag guid: (GUID fromString: '{4b1c96de-b518-4bf2-b6cf-e129ed488331}')!

SBSAccordionBodyTag comment: 'Bootstrap Accordion Body'!

!SBSAccordionBodyTag categoriesForClass!Base! !

!SBSAccordionBodyTag methodsFor!

defaultStyleClass	^ 'accordion-body'! !

!SBSAccordionBodyTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

