"Filed out from Dolphin Smalltalk"!

SBSHeadingTag subclass: #SBSAccordionHeadingTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSAccordionHeadingTag guid: (GUID fromString: '{642c2c0a-ca0c-47ab-9a5c-948b3361d2b4}')!

SBSAccordionHeadingTag comment: 'Bootstrap accordion heading'!

!SBSAccordionHeadingTag categoriesForClass!Base! !

!SBSAccordionHeadingTag methodsFor!

defaultStyleClass	^ 'accordion-heading'! !

!SBSAccordionHeadingTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

