"Filed out from Dolphin Smalltalk"!

SBSButtonTag subclass: #SBSAccordionButtonTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSAccordionButtonTag guid: (GUID fromString: '{f8283c6d-7ef0-4dc3-ad4a-c1c1d10ab070}')!

SBSAccordionButtonTag comment: 'Bootstrap Accordion Button'!

!SBSAccordionButtonTag categoriesForClass!Base! !

!SBSAccordionButtonTag methodsFor!

defaultStyleClass	^'accordion-button'! !

!SBSAccordionButtonTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

