"Filed out from Dolphin Smalltalk"!

SBSAnchorTag subclass: #SBSAlertLinkTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSAlertLinkTag guid: (GUID fromString: '{8ebb4c33-5e0a-4c33-a6c4-5151b859e9d6}')!

SBSAlertLinkTag comment: 'A boostrap alert link'!

!SBSAlertLinkTag categoriesForClass!Base! !

!SBSAlertLinkTag methodsFor!

defaultStyleClass	^'alert-link'! !

!SBSAlertLinkTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

