"Filed out from Dolphin Smalltalk"!

SBSGenericTag subclass: #SBSAccordionItemTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSAccordionItemTag guid: (GUID fromString: '{6c8d5848-8c61-4c27-9b79-5a984c4f0c64}')!

SBSAccordionItemTag comment: 'A Bootstrap accordion item component'!

!SBSAccordionItemTag categoriesForClass!Base! !

!SBSAccordionItemTag methodsFor!

defaultStyleClass	^ 'accordion-item'! !

!SBSAccordionItemTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

