"Filed out from Dolphin Smalltalk"!

SBSHeadingTag subclass: #SBSAlertHeadingTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSAlertHeadingTag guid: (GUID fromString: '{7b350fa8-d311-47ce-9424-296602d57de1}')!

SBSAlertHeadingTag comment: 'Bootstrap alert heading'!

!SBSAlertHeadingTag categoriesForClass!Base! !

!SBSAlertHeadingTag methodsFor!

defaultStyleClass	^'alert-heading'! !

!SBSAlertHeadingTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

