"Filed out from Dolphin Smalltalk"!

SBSGenericTag subclass: #SBSAccordionTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSAccordionTag guid: (GUID fromString: '{80688710-e061-4bef-91dc-15433d4dbb8d}')!

SBSAccordionTag comment: 'A Bootstrap accordion component'!

!SBSAccordionTag categoriesForClass!Base! !

!SBSAccordionTag methodsFor!

defaultStyleClass	^ 'accordion'! !

!SBSAccordionTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

