"Filed out from Dolphin Smalltalk"!

SBSGenericTag subclass: #SBSAccordionCollapseTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSAccordionCollapseTag guid: (GUID fromString: '{2ea49f88-baf2-4b34-a14b-59079dce3273}')!

SBSAccordionCollapseTag comment: 'Bootstrap Accordion Collapse'!

!SBSAccordionCollapseTag categoriesForClass!Base! !

!SBSAccordionCollapseTag methodsFor!

defaultStyleClass	^ 'accordion-collapse'! !

!SBSAccordionCollapseTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

