"Filed out from Dolphin Smalltalk"!

WAAbstractCanvasBrushTest subclass: #SBSAbstractCanvasBrushTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSAbstractCanvasBrushTest guid: (GUID fromString: '{9671a751-3691-4b05-b489-b46da585984a}')!

SBSAbstractCanvasBrushTest comment: 'Common superclass for Bootstrap4 canvas based tests'!

!SBSAbstractCanvasBrushTest categoriesForClass!Tests-Traits! !

