"Filed out from Dolphin Smalltalk"!

SBSButtonGroupTag subclass: #SBSButtonGroupVerticalTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSButtonGroupVerticalTag guid: (GUID fromString: '{457f7671-9a6c-424b-964f-527d7ff68227}')!

SBSButtonGroupVerticalTag comment: 'Vertical button group for Bootstrap'!

!SBSButtonGroupVerticalTag categoriesForClass!Base! !

!SBSButtonGroupVerticalTag methodsFor!

defaultStyleClass	^'btn-group-vertical'! !

!SBSButtonGroupVerticalTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

