"Filed out from Dolphin Smalltalk"!

SBSListItemTag subclass: #SBSBreadcrumbSectionTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSBreadcrumbSectionTag guid: (GUID fromString: '{a1fff70b-2b12-47a2-aa8e-6f34909049de}')!

SBSBreadcrumbSectionTag comment: 'A Bootstrap breadcrumb section'!

!SBSBreadcrumbSectionTag categoriesForClass!Base! !

!SBSBreadcrumbSectionTag methodsFor!

defaultStyleClass	^'breadcrumb-item'! !

!SBSBreadcrumbSectionTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

