"Filed out from Dolphin Smalltalk"!

SBSButtonGroupTag subclass: #SBSButtonToolbarTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSButtonToolbarTag guid: (GUID fromString: '{dcc35f54-0126-47b8-a5a9-14e1dabf12cb}')!

SBSButtonToolbarTag comment: 'A button toolbar'!

!SBSButtonToolbarTag categoriesForClass!Base! !

!SBSButtonToolbarTag methodsFor!

defaultStyleClass	^'btn-toolbar'! !

!SBSButtonToolbarTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

