"Filed out from Dolphin Smalltalk"!

SBSAbstractCanvasBrushTest subclass: #SBSBackgroundColorTests
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSBackgroundColorTests guid: (GUID fromString: '{eaca3b30-db5a-4d1e-845f-b21513501d4c}')!

SBSBackgroundColorTests comment: 'Tests for specific background colors'!

!SBSBackgroundColorTests categoriesForClass!Tests-Other! !

