"Filed out from Dolphin Smalltalk"!

SBSGenericTag subclass: #SBSCardDeckTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSCardDeckTag guid: (GUID fromString: '{0ae8955b-dea7-48e5-ac9b-94e3d8502354}')!

SBSCardDeckTag comment: 'Provides a grid of cards that are of equal height and width. The layout will automatically adjust as you insert more cards.'!

!SBSCardDeckTag categoriesForClass!Base! !

!SBSCardDeckTag methodsFor!

defaultStyleClass	^'card-deck'! !

!SBSCardDeckTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

