"Filed out from Dolphin Smalltalk"!

SBSGenericTag subclass: #SBSCardFooterTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSCardFooterTag guid: (GUID fromString: '{8c1e3099-5c86-4d19-a736-211c0b719872}')!

SBSCardFooterTag comment: 'Footer for Bootstrap card'!

!SBSCardFooterTag categoriesForClass!Base! !

!SBSCardFooterTag methodsFor!

defaultStyleClass	^'card-footer'! !

!SBSCardFooterTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

