"Filed out from Dolphin Smalltalk"!

SBSImageTag subclass: #SBSCardImageBottomTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSCardImageBottomTag guid: (GUID fromString: '{58af09ba-20a2-4b1c-86c5-e455242b1733}')!

SBSCardImageBottomTag comment: 'An image at the bottom of a Boostrap card'!

!SBSCardImageBottomTag categoriesForClass!Base! !

!SBSCardImageBottomTag methodsFor!

defaultStyleClass	^'card-img-bottom'! !

!SBSCardImageBottomTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

