"Filed out from Dolphin Smalltalk"!

SBSAbstractCanvasBrushTest subclass: #SBSCanvasBrushTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSCanvasBrushTest guid: (GUID fromString: '{46d34bfa-d4d6-4ab6-bbb8-5c8f5f6832bf}')!

SBSCanvasBrushTest comment: 'Tests for the Bootstrap brushes'!

!SBSCanvasBrushTest categoriesForClass!Tests-Canvas! !

