"Filed out from Dolphin Smalltalk"!

SBSGenericTag subclass: #SBSCarouselItemTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSCarouselItemTag guid: (GUID fromString: '{244a4677-aab1-491d-a804-46fb473af937}')!

SBSCarouselItemTag comment: 'A carousel item'!

!SBSCarouselItemTag categoriesForClass!Base! !

!SBSCarouselItemTag methodsFor!

active	self class: 'active'!

defaultStyleClass	^'carousel-item'! !

!SBSCarouselItemTag categoriesForMethods!
active!options!public! !
defaultStyleClass!defaults!public! !
!

