"Filed out from Dolphin Smalltalk"!

SBSCDNDeploymentLibrary subclass: #SBSCDNDeploymentLibraryRTL
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSCDNDeploymentLibraryRTL guid: (GUID fromString: '{5b82df0b-c411-4563-a523-6e0381d40281}')!

SBSCDNDeploymentLibraryRTL comment: 'Content delivery network (CDN) based deployment library with right-to-left (RTL) support'!

!SBSCDNDeploymentLibraryRTL categoriesForClass!Libraries! !

!SBSCDNDeploymentLibraryRTL class methodsFor!

cdnCSSLocation	^ 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.rtl.min.css'!

cdnCSSLocationIntegrity	"Calculated via https://www.srihash.org"	^ 'sha384-DOXMLfHhQkvFFp+rWTZwVlPVqdIhpDVYT9csOnHSgWQWPX0v5MCGtjCJbY6ERspU'! !

!SBSCDNDeploymentLibraryRTL class categoriesForMethods!
cdnCSSLocation!accessing / defaults!public! !
cdnCSSLocationIntegrity!accessing / defaults!public! !
!

