"Filed out from Dolphin Smalltalk"!

SBSGenericTag subclass: #SBSCardHeaderTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSCardHeaderTag guid: (GUID fromString: '{30e7fb07-24a0-48b5-a1f2-aacc124e7eed}')!

SBSCardHeaderTag comment: 'Header for Bootstrap card'!

!SBSCardHeaderTag categoriesForClass!Base! !

!SBSCardHeaderTag methodsFor!

defaultStyleClass	^'card-header'! !

!SBSCardHeaderTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

