"Filed out from Dolphin Smalltalk"!

SBSGenericTag subclass: #SBSCardImageOverlayTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSCardImageOverlayTag guid: (GUID fromString: '{2897be10-cfc0-4840-ba59-8045f0e3b55d}')!

SBSCardImageOverlayTag comment: 'An image overlay for a Bootstrap card'!

!SBSCardImageOverlayTag categoriesForClass!Base! !

!SBSCardImageOverlayTag methodsFor!

defaultStyleClass	^'card-img-overlay'! !

!SBSCardImageOverlayTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

