"Filed out from Dolphin Smalltalk"!

SBSGenericTag subclass: #SBSCollapseTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSCollapseTag guid: (GUID fromString: '{8a3e516f-c825-4336-aaff-2bf2266c3129}')!

SBSCollapseTag comment: 'Collapsible section'!

!SBSCollapseTag categoriesForClass!Base! !

!SBSCollapseTag methodsFor!

defaultStyleClass	^'collapse'!

show	self class: 'show'! !

!SBSCollapseTag categoriesForMethods!
defaultStyleClass!defaults!public! !
show!options!public! !
!

