"Filed out from Dolphin Smalltalk"!

SBSButtonTag subclass: #SBSCloseButtonTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSCloseButtonTag guid: (GUID fromString: '{41f9f20d-a247-483f-b817-0cd40e83cd98}')!

SBSCloseButtonTag comment: 'Bootstrap Close Button'!

!SBSCloseButtonTag categoriesForClass!Base! !

!SBSCloseButtonTag methodsFor!

defaultStyleClass	^'btn-close'! !

!SBSCloseButtonTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

