"Filed out from Dolphin Smalltalk"!

SBSAnchorTag subclass: #SBSCardLinkTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSCardLinkTag guid: (GUID fromString: '{086c48ae-d902-4b86-85f5-380c71bb8877}')!

SBSCardLinkTag comment: 'Links on Bootstrap cards'!

!SBSCardLinkTag categoriesForClass!Base! !

!SBSCardLinkTag methodsFor!

defaultStyleClass	^'card-link'! !

!SBSCardLinkTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

