"Filed out from Dolphin Smalltalk"!

SBSHeadingTag subclass: #SBSCardTitleTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSCardTitleTag guid: (GUID fromString: '{a261c336-63cf-4339-ba99-0a64c350d0f7}')!

SBSCardTitleTag comment: 'A card title'!

!SBSCardTitleTag categoriesForClass!Base! !

!SBSCardTitleTag methodsFor!

defaultStyleClass	^'card-title'! !

!SBSCardTitleTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

