"Filed out from Dolphin Smalltalk"!

SBSImageTag subclass: #SBSCardImageTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSCardImageTag guid: (GUID fromString: '{91e38790-90a6-4f90-a3b8-097da08c48d5}')!

SBSCardImageTag comment: 'An image on top of a Boostrap card'!

!SBSCardImageTag categoriesForClass!Base! !

!SBSCardImageTag methodsFor!

defaultStyleClass	^'card-img-top'! !

!SBSCardImageTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

