"Filed out from Dolphin Smalltalk"!

SBSGenericTag subclass: #SBSCardBodyTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSCardBodyTag guid: (GUID fromString: '{e2208f30-9422-460a-9137-308ecbeb55fc}')!

SBSCardBodyTag comment: 'Body of a bootstrap card.'!

!SBSCardBodyTag categoriesForClass!Base! !

!SBSCardBodyTag methodsFor!

defaultStyleClass	^'card-body'! !

!SBSCardBodyTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

