"Filed out from Dolphin Smalltalk"!

SBSGenericTag subclass: #SBSCardColumnsTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSCardColumnsTag guid: (GUID fromString: '{6f0d8dc3-14e0-44aa-9c30-be9a779fde44}')!

SBSCardColumnsTag comment: 'Creates a masonry-like grid of cards (like pinterest). The layout will automatically adjust as you insert more cards.'!

!SBSCardColumnsTag categoriesForClass!Base! !

!SBSCardColumnsTag methodsFor!

defaultStyleClass	^'card-columns'! !

!SBSCardColumnsTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

