"Filed out from Dolphin Smalltalk"!

SBSGenericTag subclass: #SBSCardGroupTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSCardGroupTag guid: (GUID fromString: '{f19f54c1-6422-4210-a8cd-522dbc6ea210}')!

SBSCardGroupTag comment: 'Similar to a card deck. The only difference is that the card group removes left and right margins between each card.'!

!SBSCardGroupTag categoriesForClass!Base! !

!SBSCardGroupTag methodsFor!

defaultStyleClass	^'card-group'! !

!SBSCardGroupTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

