"Filed out from Dolphin Smalltalk"!

SBSCardTitleTag subclass: #SBSCardSubtitleTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSCardSubtitleTag guid: (GUID fromString: '{b554fb79-a5c5-4636-915b-adba37bb71cf}')!

SBSCardSubtitleTag comment: 'Subtitle for a Bootstrap card'!

!SBSCardSubtitleTag categoriesForClass!Base! !

!SBSCardSubtitleTag methodsFor!

defaultStyleClass	^'card-subtitle'! !

!SBSCardSubtitleTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

