"Filed out from Dolphin Smalltalk"!

WAHeadingTag subclass: #SBSDisplayHeadingTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSDisplayHeadingTag guid: (GUID fromString: '{c953dde6-065f-4973-8958-77b46983ba9d}')!

SBSDisplayHeadingTag comment: 'A Bootstrap display heading'!

!SBSDisplayHeadingTag categoriesForClass!Base! !

!SBSDisplayHeadingTag methodsFor!

level: aLevel	super level: aLevel.	self class: 'display-', self level greaseString! !

!SBSDisplayHeadingTag categoriesForMethods!
level:!accessing!public! !
!

