"Filed out from Dolphin Smalltalk"!

SBSGenericTag subclass: #SBSDropdownMenuTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSDropdownMenuTag guid: (GUID fromString: '{ce236a9d-d906-4e2f-b050-5bdc47584957}')!

SBSDropdownMenuTag comment: 'Dropdown menu for Bootstrap'!

!SBSDropdownMenuTag categoriesForClass!Base! !

!SBSDropdownMenuTag methodsFor!

defaultStyleClass	^'dropdown-menu'!

dropRight	self class: 'dropdown-menu-right'! !

!SBSDropdownMenuTag categoriesForMethods!
defaultStyleClass!defaults!public! !
dropRight!options!public! !
!

