"Filed out from Dolphin Smalltalk"!

TestCase subclass: #SBSDevelopmentLibraryTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSDevelopmentLibraryTest guid: (GUID fromString: '{f998ba20-4116-4c9e-9a58-241c3af7882f}')!

SBSDevelopmentLibraryTest comment: 'SUnit test for SBSDevelopmentLibrary'!

!SBSDevelopmentLibraryTest categoriesForClass!Tests-Libraries! !

