"Filed out from Dolphin Smalltalk"!

SBSGenericTag subclass: #SBSDropdownTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSDropdownTag guid: (GUID fromString: '{1454dcca-c4f3-4b8c-ab94-c3c347852e51}')!

SBSDropdownTag comment: 'A bootstrap dropdown'!

!SBSDropdownTag categoriesForClass!Base! !

!SBSDropdownTag methodsFor!

defaultStyleClass	^'dropdown'!

dropLeft	self class: 'dropleft'!

dropRight	self class: 'dropright'!

show	self class: 'show'! !

!SBSDropdownTag categoriesForMethods!
defaultStyleClass!defaults!public! !
dropLeft!operations!public! !
dropRight!operations!public! !
show!operations!public! !
!

