"Filed out from Dolphin Smalltalk"!

SBSHeadingTag subclass: #SBSDropdownHeaderTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSDropdownHeaderTag guid: (GUID fromString: '{133bfce6-9f14-4fc1-8ddc-60b1adf402ad}')!

SBSDropdownHeaderTag comment: 'A drop down header'!

!SBSDropdownHeaderTag categoriesForClass!Base! !

!SBSDropdownHeaderTag methodsFor!

defaultStyleClass	^'dropdown-header'! !

!SBSDropdownHeaderTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

