"Filed out from Dolphin Smalltalk"!

TestCase subclass: #SBSDeploymentLibraryTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSDeploymentLibraryTest guid: (GUID fromString: '{b6b3a15d-1979-4f15-b561-7cf4da0dbc4e}')!

SBSDeploymentLibraryTest comment: 'SUnit test for SBSDeploymentLibraryTest'!

!SBSDeploymentLibraryTest categoriesForClass!Tests-Libraries! !

