"Filed out from Dolphin Smalltalk"!

SBSGenericTag subclass: #SBSDropupTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSDropupTag guid: (GUID fromString: '{db97ef45-7b69-4e4e-b733-8af1a37689b8}')!

SBSDropupTag comment: 'A bootstrap dropup'!

!SBSDropupTag categoriesForClass!Base! !

!SBSDropupTag methodsFor!

defaultStyleClass	^'dropup'! !

!SBSDropupTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

