"Filed out from Dolphin Smalltalk"!

SBSLayoutTag subclass: #SBSEqualWidthColumnsOnMultipleRowsTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSEqualWidthColumnsOnMultipleRowsTag guid: (GUID fromString: '{09ce10a6-9241-4ef3-97bc-1e065cf7c4be}')!

SBSEqualWidthColumnsOnMultipleRowsTag comment: 'Bootstrap layout row'!

!SBSEqualWidthColumnsOnMultipleRowsTag categoriesForClass!Base! !

!SBSEqualWidthColumnsOnMultipleRowsTag methodsFor!

defaultStyleClass	^'w-100'! !

!SBSEqualWidthColumnsOnMultipleRowsTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

