"Filed out from Dolphin Smalltalk"!

SBSGenericTag subclass: #SBSFormGroupTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSFormGroupTag guid: (GUID fromString: '{ae0971df-a193-4420-9a36-5251020d61a0}')!

SBSFormGroupTag comment: 'A boostrap form group'!

!SBSFormGroupTag categoriesForClass!Base! !

!SBSFormGroupTag methodsFor!

defaultStyleClass	^'form-group'!

formCheck	self class: 'form-check'! !

!SBSFormGroupTag categoriesForMethods!
defaultStyleClass!defaults!public! !
formCheck!options!public! !
!

