"Filed out from Dolphin Smalltalk"!

SBSGenericTag subclass: #SBSJumbotronTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSJumbotronTag guid: (GUID fromString: '{1cb7793d-1796-40c1-b927-5edd2881a6b3}')!

SBSJumbotronTag comment: 'Bootstrap jumbotron'!

!SBSJumbotronTag categoriesForClass!Base! !

!SBSJumbotronTag methodsFor!

defaultStyleClass	^'jumbotron'! !

!SBSJumbotronTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

