"Filed out from Dolphin Smalltalk"!

SBSGenericTag subclass: #SBSLayoutTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSLayoutTag guid: (GUID fromString: '{4942d951-0ae9-4e0d-b5ab-394f34480d88}')!

SBSLayoutTag comment: 'Abstract superclass for layout tags'!

!SBSLayoutTag categoriesForClass!Base! !

!SBSLayoutTag class methodsFor!

isAbstract	^self name = #SBSLayoutTag! !

!SBSLayoutTag class categoriesForMethods!
isAbstract!public!testing! !
!

