"Filed out from Dolphin Smalltalk"!

SBSLayoutTag subclass: #SBSLayoutRowTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSLayoutRowTag guid: (GUID fromString: '{6ee0d25c-ee86-4809-bb99-ff551bab5d8d}')!

SBSLayoutRowTag comment: 'A boostrap layout row'!

!SBSLayoutRowTag categoriesForClass!Bootstrap5-Core-Base! !

!SBSLayoutRowTag methodsFor!

alignItemsBaseline	self class: 'align-items-baseline'!

alignItemsBaselineLarge	self class: 'align-items-lg-baseline'!

alignItemsBaselineMedium	self class: 'align-items-md-baseline'!

alignItemsBaselineSmall	self class: 'align-items-sm-baseline'!

alignItemsBaselineVeryLarge	self class: 'align-items-xl-baseline'!

alignItemsCenter	self class: 'align-items-center'!

alignItemsCenterLarge	self class: 'align-items-lg-center'!

alignItemsCenterMedium	self class: 'align-items-md-center'!

alignItemsCenterSmall	self class: 'align-items-sm-center'!

alignItemsCenterVeryLarge	self class: 'align-items-xl-center'!

alignItemsEnd	self class: 'align-items-end'!

alignItemsEndLarge	self class: 'align-items-lg-end'!

alignItemsEndMedium	self class: 'align-items-md-end'!

alignItemsEndSmall	self class: 'align-items-sm-end'!

alignItemsEndVeryLarge	self class: 'align-items-xl-end'!

alignItemsStart	self class: 'align-items-start'!

alignItemsStartLarge	self class: 'align-items-lg-start'!

alignItemsStartMedium	self class: 'align-items-md-start'!

alignItemsStartSmall	self class: 'align-items-sm-start'!

alignItemsStartVeryLarge	self class: 'align-items-xl-start'!

alignItemsStretch	self class: 'align-items-stretch'!

alignItemsStretchLarge	self class: 'align-items-lg-stretch'!

alignItemsStretchMedium	self class: 'align-items-md-stretch'!

alignItemsStretchSmall	self class: 'align-items-sm-stretch'!

alignItemsStretchVeryLarge	self class: 'align-items-xl-stretch'!

defaultStyleClass	^'row'!

justifyContentAround	self class: 'justify-content-around'!

justifyContentAroundLarge	self class: 'justify-content-lg-around'!

justifyContentAroundMedium	self class: 'justify-content-md-around'!

justifyContentAroundSmall	self class: 'justify-content-sm-around'!

justifyContentAroundVeryLarge	self class: 'justify-content-xl-around'!

justifyContentBetween	self class: 'justify-content-between'!

justifyContentBetweenLarge	self class: 'justify-content-lg-between'!

justifyContentBetweenMedium	self class: 'justify-content-md-between'!

justifyContentBetweenSmall	self class: 'justify-content-sm-between'!

justifyContentBetweenVeryLarge	self class: 'justify-content-xl-between'!

justifyContentCenter	self class: 'justify-content-center'!

justifyContentCenterLarge	self class: 'justify-content-lg-center'!

justifyContentCenterMedium	self class: 'justify-content-md-center'!

justifyContentCenterSmall	self class: 'justify-content-sm-center'!

justifyContentCenterVeryLarge	self class: 'justify-content-xl-center'!

justifyContentEnd	self class: 'justify-content-end'!

justifyContentEndLarge	self class: 'justify-content-lg-end'!

justifyContentEndMedium	self class: 'justify-content-md-end'!

justifyContentEndSmall	self class: 'justify-content-sm-end'!

justifyContentEndVeryLarge	self class: 'justify-content-xl-end'!

justifyContentStart	self class: 'justify-content-start'!

justifyContentStartLarge	self class: 'justify-content-lg-start'!

justifyContentStartMedium	self class: 'justify-content-md-start'!

justifyContentStartSmall	self class: 'justify-content-sm-start'!

justifyContentStartVeryLarge	self class: 'justify-content-xl-start'!

noGutters	self class: 'no-gutters'! !

!SBSLayoutRowTag categoriesForMethods!
alignItemsBaseline!alignment vertical!public! !
alignItemsBaselineLarge!alignment vertical!public! !
alignItemsBaselineMedium!alignment vertical!public! !
alignItemsBaselineSmall!alignment vertical!public! !
alignItemsBaselineVeryLarge!alignment vertical!public! !
alignItemsCenter!alignment vertical!public! !
alignItemsCenterLarge!alignment vertical!public! !
alignItemsCenterMedium!alignment vertical!public! !
alignItemsCenterSmall!alignment vertical!public! !
alignItemsCenterVeryLarge!alignment vertical!public! !
alignItemsEnd!alignment vertical!public! !
alignItemsEndLarge!alignment vertical!public! !
alignItemsEndMedium!alignment vertical!public! !
alignItemsEndSmall!alignment vertical!public! !
alignItemsEndVeryLarge!alignment vertical!public! !
alignItemsStart!alignment vertical!public! !
alignItemsStartLarge!alignment vertical!public! !
alignItemsStartMedium!alignment vertical!public! !
alignItemsStartSmall!alignment vertical!public! !
alignItemsStartVeryLarge!alignment vertical!public! !
alignItemsStretch!alignment vertical!public! !
alignItemsStretchLarge!alignment vertical!public! !
alignItemsStretchMedium!alignment vertical!public! !
alignItemsStretchSmall!alignment vertical!public! !
alignItemsStretchVeryLarge!alignment vertical!public! !
defaultStyleClass!defaults!public! !
justifyContentAround!alignment horizontal!public! !
justifyContentAroundLarge!alignment horizontal!public! !
justifyContentAroundMedium!alignment horizontal!public! !
justifyContentAroundSmall!alignment horizontal!public! !
justifyContentAroundVeryLarge!alignment horizontal!public! !
justifyContentBetween!alignment horizontal!public! !
justifyContentBetweenLarge!alignment horizontal!public! !
justifyContentBetweenMedium!alignment horizontal!public! !
justifyContentBetweenSmall!alignment horizontal!public! !
justifyContentBetweenVeryLarge!alignment horizontal!public! !
justifyContentCenter!alignment horizontal!public! !
justifyContentCenterLarge!alignment horizontal!public! !
justifyContentCenterMedium!alignment horizontal!public! !
justifyContentCenterSmall!alignment horizontal!public! !
justifyContentCenterVeryLarge!alignment horizontal!public! !
justifyContentEnd!alignment horizontal!public! !
justifyContentEndLarge!alignment horizontal!public! !
justifyContentEndMedium!alignment horizontal!public! !
justifyContentEndSmall!alignment horizontal!public! !
justifyContentEndVeryLarge!alignment horizontal!public! !
justifyContentStart!alignment horizontal!public! !
justifyContentStartLarge!alignment horizontal!public! !
justifyContentStartMedium!alignment horizontal!public! !
justifyContentStartSmall!alignment horizontal!public! !
justifyContentStartVeryLarge!alignment horizontal!public! !
noGutters!options!public! !
!

