"Filed out from Dolphin Smalltalk"!

SBSHeadingTag subclass: #SBSModalTitleTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSModalTitleTag guid: (GUID fromString: '{223bc70e-7491-4662-8501-028ad1b8f2d3}')!

SBSModalTitleTag comment: 'Bootstrap Modal Title'!

!SBSModalTitleTag categoriesForClass!Base! !

!SBSModalTitleTag methodsFor!

defaultStyleClass	^'modal-title'! !

!SBSModalTitleTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

