"Filed out from Dolphin Smalltalk"!

SBSGenericTag subclass: #SBSNavigationBarCollapseTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSNavigationBarCollapseTag guid: (GUID fromString: '{bd30ad21-6544-4902-933a-05ff7c643f83}')!

SBSNavigationBarCollapseTag comment: 'Used for grouping and hiding navbar contents by a parent breakpoint'!

!SBSNavigationBarCollapseTag categoriesForClass!Base! !

!SBSNavigationBarCollapseTag methodsFor!

collapse	self class: 'collapse'!

defaultStyleClass	^'navbar-collapse'! !

!SBSNavigationBarCollapseTag categoriesForMethods!
collapse!options!public! !
defaultStyleClass!defaults!public! !
!

