"Filed out from Dolphin Smalltalk"!

SBSAnchorTag subclass: #SBSNavigationBarBrandTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSNavigationBarBrandTag guid: (GUID fromString: '{e23d0c4d-a4a6-4c63-b11b-ac0a7d1338b0}')!

SBSNavigationBarBrandTag comment: 'Clickable navigation bar brand'!

!SBSNavigationBarBrandTag categoriesForClass!Base! !

!SBSNavigationBarBrandTag methodsFor!

defaultStyleClass	^'navbar-brand'! !

!SBSNavigationBarBrandTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

