"Filed out from Dolphin Smalltalk"!

SBSUnorderedListTag subclass: #SBSNavigationTabTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSNavigationTabTag guid: (GUID fromString: '{59551bcf-9447-4614-a3d4-cdcf2edf12fa}')!

SBSNavigationTabTag comment: 'I''m a Bootstrap navigation tab item.'!

!SBSNavigationTabTag categoriesForClass!Bootstrap5-Core-Base! !

!SBSNavigationTabTag methodsFor!

defaultStyleClass	^'nav nav-tabs'!

initialize	super initialize.	self attributeAt: 'role' put: 'tablist'!

justifyContentAround	self class: 'justify-content-around'!

justifyContentAroundLarge	self class: 'justify-content-lg-around'!

justifyContentAroundMedium	self class: 'justify-content-md-around'!

justifyContentAroundSmall	self class: 'justify-content-sm-around'!

justifyContentAroundVeryLarge	self class: 'justify-content-xl-around'!

justifyContentBetween	self class: 'justify-content-between'!

justifyContentBetweenLarge	self class: 'justify-content-lg-between'!

justifyContentBetweenMedium	self class: 'justify-content-md-between'!

justifyContentBetweenSmall	self class: 'justify-content-sm-between'!

justifyContentBetweenVeryLarge	self class: 'justify-content-xl-between'!

justifyContentCenter	self class: 'justify-content-center'!

justifyContentCenterLarge	self class: 'justify-content-lg-center'!

justifyContentCenterMedium	self class: 'justify-content-md-center'!

justifyContentCenterSmall	self class: 'justify-content-sm-center'!

justifyContentCenterVeryLarge	self class: 'justify-content-xl-center'!

justifyContentEnd	self class: 'justify-content-end'!

justifyContentEndLarge	self class: 'justify-content-lg-end'!

justifyContentEndMedium	self class: 'justify-content-md-end'!

justifyContentEndSmall	self class: 'justify-content-sm-end'!

justifyContentEndVeryLarge	self class: 'justify-content-xl-end'!

justifyContentStart	self class: 'justify-content-start'!

justifyContentStartLarge	self class: 'justify-content-lg-start'!

justifyContentStartMedium	self class: 'justify-content-md-start'!

justifyContentStartSmall	self class: 'justify-content-sm-start'!

justifyContentStartVeryLarge	self class: 'justify-content-xl-start'! !

!SBSNavigationTabTag categoriesForMethods!
defaultStyleClass!defaults!public! !
initialize!initialization!public! !
justifyContentAround!alignment horizontal!public! !
justifyContentAroundLarge!alignment horizontal!public! !
justifyContentAroundMedium!alignment horizontal!public! !
justifyContentAroundSmall!alignment horizontal!public! !
justifyContentAroundVeryLarge!alignment horizontal!public! !
justifyContentBetween!alignment horizontal!public! !
justifyContentBetweenLarge!alignment horizontal!public! !
justifyContentBetweenMedium!alignment horizontal!public! !
justifyContentBetweenSmall!alignment horizontal!public! !
justifyContentBetweenVeryLarge!alignment horizontal!public! !
justifyContentCenter!alignment horizontal!public! !
justifyContentCenterLarge!alignment horizontal!public! !
justifyContentCenterMedium!alignment horizontal!public! !
justifyContentCenterSmall!alignment horizontal!public! !
justifyContentCenterVeryLarge!alignment horizontal!public! !
justifyContentEnd!alignment horizontal!public! !
justifyContentEndLarge!alignment horizontal!public! !
justifyContentEndMedium!alignment horizontal!public! !
justifyContentEndSmall!alignment horizontal!public! !
justifyContentEndVeryLarge!alignment horizontal!public! !
justifyContentStart!alignment horizontal!public! !
justifyContentStartLarge!alignment horizontal!public! !
justifyContentStartMedium!alignment horizontal!public! !
justifyContentStartSmall!alignment horizontal!public! !
justifyContentStartVeryLarge!alignment horizontal!public! !
!

