"Filed out from Dolphin Smalltalk"!

SBSNavTag subclass: #SBSNavigationTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSNavigationTag guid: (GUID fromString: '{76870e81-1727-4745-8fa8-603c54c060b5}')!

SBSNavigationTag comment: 'Bootstrap navigation'!

!SBSNavigationTag categoriesForClass!Bootstrap5-Core-Base! !

!SBSNavigationTag methodsFor!

defaultStyleClass	^'nav'!

flex	self class: 'd-flex'!

flexColumn	self class: 'flex-column'!

flexColumnLarge	self class: 'flex-lg-column'!

flexColumnLargeReverse	self class: 'flex-lg-column-reverse'!

flexColumnMedium	self class: 'flex-md-column'!

flexColumnMediumReverse	self class: 'flex-md-column-reverse'!

flexColumnReverse	self class: 'flex-column-reverse'!

flexColumnSmall	self class: 'flex-sm-column'!

flexColumnSmallReverse	self class: 'flex-sm-column-reverse'!

flexColumnVeryLarge	self class: 'flex-xl-column'!

flexColumnVeryLargeReverse	self class: 'flex-xl-column-reverse'!

flexInline	self class: 'd-inline-flex'!

flexLarge	self class: 'd-lg-flex'!

flexLargeInline	self class: 'd-lg-inline-flex'!

flexMedium	self class: 'd-md-flex'!

flexMediumInline	self class: 'd-md-inline-flex'!

flexRow	self class: 'flex-row'!

flexRowLarge	self class: 'flex-lg-row'!

flexRowLargeReverse	self class: 'flex-lg-row-reverse'!

flexRowMedium	self class: 'flex-md-row'!

flexRowMediumReverse	self class: 'flex-md-row-reverse'!

flexRowReverse	self class: 'flex-row-reverse'!

flexRowSmall	self class: 'flex-sm-row'!

flexRowSmallReverse	self class: 'flex-sm-row-reverse'!

flexRowVeryLarge	self class: 'flex-xl-row'!

flexRowVeryLargeReverse	self class: 'flex-xl-row-reverse'!

flexSmall	self class: 'd-sm-flex'!

flexSmallInline	self class: 'd-sm-inline-flex'!

flexVeryLarge	self class: 'd-xl-flex'!

flexVeryLargeInline	self class: 'd-xl-inline-flex'!

initialize	super initialize.	self class: self defaultStyleClass!

justifyContentAround	self class: 'justify-content-around'!

justifyContentAroundLarge	self class: 'justify-content-lg-around'!

justifyContentAroundMedium	self class: 'justify-content-md-around'!

justifyContentAroundSmall	self class: 'justify-content-sm-around'!

justifyContentAroundVeryLarge	self class: 'justify-content-xl-around'!

justifyContentBetween	self class: 'justify-content-between'!

justifyContentBetweenLarge	self class: 'justify-content-lg-between'!

justifyContentBetweenMedium	self class: 'justify-content-md-between'!

justifyContentBetweenSmall	self class: 'justify-content-sm-between'!

justifyContentBetweenVeryLarge	self class: 'justify-content-xl-between'!

justifyContentCenter	self class: 'justify-content-center'!

justifyContentCenterLarge	self class: 'justify-content-lg-center'!

justifyContentCenterMedium	self class: 'justify-content-md-center'!

justifyContentCenterSmall	self class: 'justify-content-sm-center'!

justifyContentCenterVeryLarge	self class: 'justify-content-xl-center'!

justifyContentEnd	self class: 'justify-content-end'!

justifyContentEndLarge	self class: 'justify-content-lg-end'!

justifyContentEndMedium	self class: 'justify-content-md-end'!

justifyContentEndSmall	self class: 'justify-content-sm-end'!

justifyContentEndVeryLarge	self class: 'justify-content-xl-end'!

justifyContentStart	self class: 'justify-content-start'!

justifyContentStartLarge	self class: 'justify-content-lg-start'!

justifyContentStartMedium	self class: 'justify-content-md-start'!

justifyContentStartSmall	self class: 'justify-content-sm-start'!

justifyContentStartVeryLarge	self class: 'justify-content-xl-start'! !

!SBSNavigationTag categoriesForMethods!
defaultStyleClass!defaults!public! !
flex!container!public! !
flexColumn!alignment direction!public! !
flexColumnLarge!alignment direction!public! !
flexColumnLargeReverse!alignment direction!public! !
flexColumnMedium!alignment direction!public! !
flexColumnMediumReverse!alignment direction!public! !
flexColumnReverse!alignment direction!public! !
flexColumnSmall!alignment direction!public! !
flexColumnSmallReverse!alignment direction!public! !
flexColumnVeryLarge!alignment direction!public! !
flexColumnVeryLargeReverse!alignment direction!public! !
flexInline!container!public! !
flexLarge!container!public! !
flexLargeInline!container!public! !
flexMedium!container!public! !
flexMediumInline!container!public! !
flexRow!alignment direction!public! !
flexRowLarge!alignment direction!public! !
flexRowLargeReverse!alignment direction!public! !
flexRowMedium!alignment direction!public! !
flexRowMediumReverse!alignment direction!public! !
flexRowReverse!alignment direction!public! !
flexRowSmall!alignment direction!public! !
flexRowSmallReverse!alignment direction!public! !
flexRowVeryLarge!alignment direction!public! !
flexRowVeryLargeReverse!alignment direction!public! !
flexSmall!container!public! !
flexSmallInline!container!public! !
flexVeryLarge!container!public! !
flexVeryLargeInline!container!public! !
initialize!initialization!public! !
justifyContentAround!alignment horizontal!public! !
justifyContentAroundLarge!alignment horizontal!public! !
justifyContentAroundMedium!alignment horizontal!public! !
justifyContentAroundSmall!alignment horizontal!public! !
justifyContentAroundVeryLarge!alignment horizontal!public! !
justifyContentBetween!alignment horizontal!public! !
justifyContentBetweenLarge!alignment horizontal!public! !
justifyContentBetweenMedium!alignment horizontal!public! !
justifyContentBetweenSmall!alignment horizontal!public! !
justifyContentBetweenVeryLarge!alignment horizontal!public! !
justifyContentCenter!alignment horizontal!public! !
justifyContentCenterLarge!alignment horizontal!public! !
justifyContentCenterMedium!alignment horizontal!public! !
justifyContentCenterSmall!alignment horizontal!public! !
justifyContentCenterVeryLarge!alignment horizontal!public! !
justifyContentEnd!alignment horizontal!public! !
justifyContentEndLarge!alignment horizontal!public! !
justifyContentEndMedium!alignment horizontal!public! !
justifyContentEndSmall!alignment horizontal!public! !
justifyContentEndVeryLarge!alignment horizontal!public! !
justifyContentStart!alignment horizontal!public! !
justifyContentStartLarge!alignment horizontal!public! !
justifyContentStartMedium!alignment horizontal!public! !
justifyContentStartSmall!alignment horizontal!public! !
justifyContentStartVeryLarge!alignment horizontal!public! !
!

