"Filed out from Dolphin Smalltalk"!

SBSButtonTag subclass: #SBSOutlineButtonTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSOutlineButtonTag guid: (GUID fromString: '{a1a5de9f-2560-4de4-9449-277c9d758a8e}')!

SBSOutlineButtonTag comment: 'Bootstrap outlined buttons. It is like a regular form button - but by giving additional style options like bePrimary, or beSecondary, ... the button willhave an outlined look.'!

!SBSOutlineButtonTag categoriesForClass!Base! !

!SBSOutlineButtonTag methodsFor!

defaultModifier	^'outline'! !

!SBSOutlineButtonTag categoriesForMethods!
defaultModifier!defaults!public! !
!

