"Filed out from Dolphin Smalltalk"!

SBSListItemTag subclass: #SBSPageItemTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSPageItemTag guid: (GUID fromString: '{07bfdb68-79bd-4b0e-88ae-2b3f97e7d42c}')!

SBSPageItemTag comment: 'A page item for pagination'!

!SBSPageItemTag categoriesForClass!Base! !

!SBSPageItemTag methodsFor!

defaultStyleClass	^'page-item'! !

!SBSPageItemTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

