"Filed out from Dolphin Smalltalk"!

SBSAnchorTag subclass: #SBSPageLinkTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSPageLinkTag guid: (GUID fromString: '{4873affc-3116-49f5-b3ec-96e5fd0dbce1}')!

SBSPageLinkTag comment: 'A page link for Bootstrap pagination'!

!SBSPageLinkTag categoriesForClass!Base! !

!SBSPageLinkTag methodsFor!

defaultStyleClass	^'page-link'! !

!SBSPageLinkTag categoriesForMethods!
defaultStyleClass!defaults!public! !
!

