"Filed out from Dolphin Smalltalk"!

TestCase subclass: #SBSRootComponentTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSRootComponentTest guid: (GUID fromString: '{16a57d4b-c684-4add-b1c1-8662a771eb22}')!

SBSRootComponentTest comment: 'SUnit tests for SBSRootComponent'!

!SBSRootComponentTest categoriesForClass!Tests-Component! !

