"Filed out from Dolphin Smalltalk"!

Trait subclass: #SBSTRowItemAlignment
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSTRowItemAlignment guid: (GUID fromString: '{18a5f518-b177-434f-856b-741a9da57473}')!

SBSTRowItemAlignment comment: 'Vertical alignment of items in a row'!

!SBSTRowItemAlignment categoriesForClass!Unclassified! !

!SBSTRowItemAlignment methodsFor!

alignItemsBaseline	self class: 'align-items-baseline'!

alignItemsBaselineLarge	self class: 'align-items-lg-baseline'!

alignItemsBaselineMedium	self class: 'align-items-md-baseline'!

alignItemsBaselineSmall	self class: 'align-items-sm-baseline'!

alignItemsBaselineVeryLarge	self class: 'align-items-xl-baseline'!

alignItemsCenter	self class: 'align-items-center'!

alignItemsCenterLarge	self class: 'align-items-lg-center'!

alignItemsCenterMedium	self class: 'align-items-md-center'!

alignItemsCenterSmall	self class: 'align-items-sm-center'!

alignItemsCenterVeryLarge	self class: 'align-items-xl-center'!

alignItemsEnd	self class: 'align-items-end'!

alignItemsEndLarge	self class: 'align-items-lg-end'!

alignItemsEndMedium	self class: 'align-items-md-end'!

alignItemsEndSmall	self class: 'align-items-sm-end'!

alignItemsEndVeryLarge	self class: 'align-items-xl-end'!

alignItemsStart	self class: 'align-items-start'!

alignItemsStartLarge	self class: 'align-items-lg-start'!

alignItemsStartMedium	self class: 'align-items-md-start'!

alignItemsStartSmall	self class: 'align-items-sm-start'!

alignItemsStartVeryLarge	self class: 'align-items-xl-start'!

alignItemsStretch	self class: 'align-items-stretch'!

alignItemsStretchLarge	self class: 'align-items-lg-stretch'!

alignItemsStretchMedium	self class: 'align-items-md-stretch'!

alignItemsStretchSmall	self class: 'align-items-sm-stretch'!

alignItemsStretchVeryLarge	self class: 'align-items-xl-stretch'! !

!SBSTRowItemAlignment categoriesForMethods!
alignItemsBaseline!alignment vertical!public! !
alignItemsBaselineLarge!alignment vertical!public! !
alignItemsBaselineMedium!alignment vertical!public! !
alignItemsBaselineSmall!alignment vertical!public! !
alignItemsBaselineVeryLarge!alignment vertical!public! !
alignItemsCenter!alignment vertical!public! !
alignItemsCenterLarge!alignment vertical!public! !
alignItemsCenterMedium!alignment vertical!public! !
alignItemsCenterSmall!alignment vertical!public! !
alignItemsCenterVeryLarge!alignment vertical!public! !
alignItemsEnd!alignment vertical!public! !
alignItemsEndLarge!alignment vertical!public! !
alignItemsEndMedium!alignment vertical!public! !
alignItemsEndSmall!alignment vertical!public! !
alignItemsEndVeryLarge!alignment vertical!public! !
alignItemsStart!alignment vertical!public! !
alignItemsStartLarge!alignment vertical!public! !
alignItemsStartMedium!alignment vertical!public! !
alignItemsStartSmall!alignment vertical!public! !
alignItemsStartVeryLarge!alignment vertical!public! !
alignItemsStretch!alignment vertical!public! !
alignItemsStretchLarge!alignment vertical!public! !
alignItemsStretchMedium!alignment vertical!public! !
alignItemsStretchSmall!alignment vertical!public! !
alignItemsStretchVeryLarge!alignment vertical!public! !
!

