"Filed out from Dolphin Smalltalk"!

Trait subclass: #SBSTContentJustification
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSTContentJustification guid: (GUID fromString: '{5d287c23-6147-431f-be19-fa54b79613e1}')!

SBSTContentJustification comment: 'A trait for flexbox alignment'!

!SBSTContentJustification categoriesForClass!Unclassified! !

!SBSTContentJustification methodsFor!

justifyContentAround	self class: 'justify-content-around'!

justifyContentAroundLarge	self class: 'justify-content-lg-around'!

justifyContentAroundMedium	self class: 'justify-content-md-around'!

justifyContentAroundSmall	self class: 'justify-content-sm-around'!

justifyContentAroundVeryLarge	self class: 'justify-content-xl-around'!

justifyContentBetween	self class: 'justify-content-between'!

justifyContentBetweenLarge	self class: 'justify-content-lg-between'!

justifyContentBetweenMedium	self class: 'justify-content-md-between'!

justifyContentBetweenSmall	self class: 'justify-content-sm-between'!

justifyContentBetweenVeryLarge	self class: 'justify-content-xl-between'!

justifyContentCenter	self class: 'justify-content-center'!

justifyContentCenterLarge	self class: 'justify-content-lg-center'!

justifyContentCenterMedium	self class: 'justify-content-md-center'!

justifyContentCenterSmall	self class: 'justify-content-sm-center'!

justifyContentCenterVeryLarge	self class: 'justify-content-xl-center'!

justifyContentEnd	self class: 'justify-content-end'!

justifyContentEndLarge	self class: 'justify-content-lg-end'!

justifyContentEndMedium	self class: 'justify-content-md-end'!

justifyContentEndSmall	self class: 'justify-content-sm-end'!

justifyContentEndVeryLarge	self class: 'justify-content-xl-end'!

justifyContentStart	self class: 'justify-content-start'!

justifyContentStartLarge	self class: 'justify-content-lg-start'!

justifyContentStartMedium	self class: 'justify-content-md-start'!

justifyContentStartSmall	self class: 'justify-content-sm-start'!

justifyContentStartVeryLarge	self class: 'justify-content-xl-start'! !

!SBSTContentJustification categoriesForMethods!
justifyContentAround!alignment horizontal!public! !
justifyContentAroundLarge!alignment horizontal!public! !
justifyContentAroundMedium!alignment horizontal!public! !
justifyContentAroundSmall!alignment horizontal!public! !
justifyContentAroundVeryLarge!alignment horizontal!public! !
justifyContentBetween!alignment horizontal!public! !
justifyContentBetweenLarge!alignment horizontal!public! !
justifyContentBetweenMedium!alignment horizontal!public! !
justifyContentBetweenSmall!alignment horizontal!public! !
justifyContentBetweenVeryLarge!alignment horizontal!public! !
justifyContentCenter!alignment horizontal!public! !
justifyContentCenterLarge!alignment horizontal!public! !
justifyContentCenterMedium!alignment horizontal!public! !
justifyContentCenterSmall!alignment horizontal!public! !
justifyContentCenterVeryLarge!alignment horizontal!public! !
justifyContentEnd!alignment horizontal!public! !
justifyContentEndLarge!alignment horizontal!public! !
justifyContentEndMedium!alignment horizontal!public! !
justifyContentEndSmall!alignment horizontal!public! !
justifyContentEndVeryLarge!alignment horizontal!public! !
justifyContentStart!alignment horizontal!public! !
justifyContentStartLarge!alignment horizontal!public! !
justifyContentStartMedium!alignment horizontal!public! !
justifyContentStartSmall!alignment horizontal!public! !
justifyContentStartVeryLarge!alignment horizontal!public! !
!

