"Filed out from Dolphin Smalltalk"!

SBSAbstractCanvasBrushTest subclass: #SBSTOffsettingTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSTOffsettingTest guid: (GUID fromString: '{54423d57-c882-48d3-a8aa-7afb01738223}')!

SBSTOffsettingTest comment: 'SUnit tests for SBSTOffsetting'!

!SBSTOffsettingTest categoriesForClass!Tests-Traits! !

