"Filed out from Dolphin Smalltalk"!

SBSAbstractCanvasBrushTest subclass: #SBSTContentJustificationTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSTContentJustificationTest guid: (GUID fromString: '{29494726-20bc-4a3b-aff8-4c436bf52e09}')!

SBSTContentJustificationTest comment: 'SUnit tests for SBSTHorizontalAlignable trait'!

!SBSTContentJustificationTest categoriesForClass!Tests-Traits! !

