"Filed out from Dolphin Smalltalk"!

WAAbstractCanvasBrushTest subclass: #SBSTextColorTests
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSTextColorTests guid: (GUID fromString: '{a2bbaa64-1c7b-44f7-b2ad-37d88b2b5a5c}')!

SBSTextColorTests comment: 'Tests for text color extensions'!

!SBSTextColorTests categoriesForClass!Tests-Other! !

