"Filed out from Dolphin Smalltalk"!

SBSAbstractCanvasBrushTest subclass: #SBSTColumnSelfAlignmentTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSTColumnSelfAlignmentTest guid: (GUID fromString: '{bc71bdbe-1c92-493d-9924-3810a591a42f}')!

SBSTColumnSelfAlignmentTest comment: 'SUnit tests for SBSTColumnSelfAlignment'!

!SBSTColumnSelfAlignmentTest categoriesForClass!Tests-Traits! !

