"Filed out from Dolphin Smalltalk"!

SBSAbstractCanvasBrushTest subclass: #SBSTVisualOrderTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSTVisualOrderTest guid: (GUID fromString: '{7a0aa90a-1464-4514-a5a0-c08e04c10c0e}')!

SBSTVisualOrderTest comment: 'SUnit tests for SBSTVisualOrder'!

!SBSTVisualOrderTest categoriesForClass!Tests-Traits! !

