"Filed out from Dolphin Smalltalk"!

Trait subclass: #SBSTColumnSelfAlignment
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSTColumnSelfAlignment guid: (GUID fromString: '{cebca22f-e7a8-4619-87a5-8d158c379ca9}')!

SBSTColumnSelfAlignment comment: 'Vertical alignment classes for columns'!

!SBSTColumnSelfAlignment categoriesForClass!Unclassified! !

!SBSTColumnSelfAlignment methodsFor!

alignCenter	self class: 'align-self-center'!

alignEnd	self class: 'align-self-end'!

alignStart	self class: 'align-self-start'! !

!SBSTColumnSelfAlignment categoriesForMethods!
alignCenter!alignment vertical!public! !
alignEnd!alignment vertical!public! !
alignStart!alignment vertical!public! !
!

