"Filed out from Dolphin Smalltalk"!

Trait subclass: #SBSTFlexboxContainer
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSTFlexboxContainer guid: (GUID fromString: '{b4216d58-2d1d-4b20-945e-bb0727a22bb5}')!

SBSTFlexboxContainer comment: 'A trait for flexbox container behaviour'!

!SBSTFlexboxContainer categoriesForClass!Unclassified! !

!SBSTFlexboxContainer methodsFor!

flex	self class: 'd-flex'!

flexColumn	self class: 'flex-column'!

flexColumnLarge	self class: 'flex-lg-column'!

flexColumnLargeReverse	self class: 'flex-lg-column-reverse'!

flexColumnMedium	self class: 'flex-md-column'!

flexColumnMediumReverse	self class: 'flex-md-column-reverse'!

flexColumnReverse	self class: 'flex-column-reverse'!

flexColumnSmall	self class: 'flex-sm-column'!

flexColumnSmallReverse	self class: 'flex-sm-column-reverse'!

flexColumnVeryLarge	self class: 'flex-xl-column'!

flexColumnVeryLargeReverse	self class: 'flex-xl-column-reverse'!

flexInline	self class: 'd-inline-flex'!

flexLarge	self class: 'd-lg-flex'!

flexLargeInline	self class: 'd-lg-inline-flex'!

flexMedium	self class: 'd-md-flex'!

flexMediumInline	self class: 'd-md-inline-flex'!

flexRow	self class: 'flex-row'!

flexRowLarge	self class: 'flex-lg-row'!

flexRowLargeReverse	self class: 'flex-lg-row-reverse'!

flexRowMedium	self class: 'flex-md-row'!

flexRowMediumReverse	self class: 'flex-md-row-reverse'!

flexRowReverse	self class: 'flex-row-reverse'!

flexRowSmall	self class: 'flex-sm-row'!

flexRowSmallReverse	self class: 'flex-sm-row-reverse'!

flexRowVeryLarge	self class: 'flex-xl-row'!

flexRowVeryLargeReverse	self class: 'flex-xl-row-reverse'!

flexSmall	self class: 'd-sm-flex'!

flexSmallInline	self class: 'd-sm-inline-flex'!

flexVeryLarge	self class: 'd-xl-flex'!

flexVeryLargeInline	self class: 'd-xl-inline-flex'! !

!SBSTFlexboxContainer categoriesForMethods!
flex!container!public! !
flexColumn!alignment direction!public! !
flexColumnLarge!alignment direction!public! !
flexColumnLargeReverse!alignment direction!public! !
flexColumnMedium!alignment direction!public! !
flexColumnMediumReverse!alignment direction!public! !
flexColumnReverse!alignment direction!public! !
flexColumnSmall!alignment direction!public! !
flexColumnSmallReverse!alignment direction!public! !
flexColumnVeryLarge!alignment direction!public! !
flexColumnVeryLargeReverse!alignment direction!public! !
flexInline!container!public! !
flexLarge!container!public! !
flexLargeInline!container!public! !
flexMedium!container!public! !
flexMediumInline!container!public! !
flexRow!alignment direction!public! !
flexRowLarge!alignment direction!public! !
flexRowLargeReverse!alignment direction!public! !
flexRowMedium!alignment direction!public! !
flexRowMediumReverse!alignment direction!public! !
flexRowReverse!alignment direction!public! !
flexRowSmall!alignment direction!public! !
flexRowSmallReverse!alignment direction!public! !
flexRowVeryLarge!alignment direction!public! !
flexRowVeryLargeReverse!alignment direction!public! !
flexSmall!container!public! !
flexSmallInline!container!public! !
flexVeryLarge!container!public! !
flexVeryLargeInline!container!public! !
!

