"Filed out from Dolphin Smalltalk"!

SBSAbstractCanvasBrushTest subclass: #SBSTRowItemAlignmentTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSTRowItemAlignmentTest guid: (GUID fromString: '{c868dcdc-e15b-44d9-9bcc-65eda36aa14c}')!

SBSTRowItemAlignmentTest comment: 'SUnit tests for SBSTRowItemAlignment'!

!SBSTRowItemAlignmentTest categoriesForClass!Tests-Traits! !

